### ISSUE TITLE
What does it mean when a certain event does not have a corresponding 360 frame entry? [Open data]

### ISSUE THREAD

**Issue by wwwidonja** [statsbomb/statsbombpy#55]
### Version

1.0.1

### What platform are you seeing the problem on?

Windows

### What Python version are you running, are you using a virtual environment? Give us as much info as you can.

Python 3.8. No special packages, using latest statsbombpy distribution

### What happened?

Hi,
I've noticed that there are several events (in the example below, ~half of the passes in the 2022 WC final, as seen in the reproducable code) without a matching 360 frame entry. Is this by design, meaning that they simply were not tracked? Or am I interfacing with the package in an incorrect manner and there are additional frames available elsewhere? Is there any way to interpret the selection of events that was made in the tracking (ie. -did all unavailable passes happen off camera?)

Kind regards!

### Code to reproduce issue

```shell
from statsbombpy import sb

## select events and frames from a given match
events = sb.events(3869685, split=True, flatten_attrs=True)['passes']
frames = sb.frames(3869685)

##fetch all ids for events, for which there are available frames
frames_ids = frames['id'].unique()

##filter the events dataframe based on the frame ids: return only the events without matching entries in the frames dataframe.
events.loc[~events.id.isin(frames_ids)]```
```

**Comment by scotty779** [comment]
Thank you for reporting this. This was a bug which we've now fixed. If you reimport the data the missing frames should be in the dataset now.

**Comment by wwwidonja** [comment]
Hi,
Thank you for your response, however, I'm still seeing this issue. The code provided in the example above yields all such passes without an associated frame. In this case, I'm getting 265 / ~12k such events. 

Is this expected behavior? If so, is there an explanation of which kind of passes this is present for?
